services:
  api:
    image: deployment-api
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ${MODEL_PATH}:/models/model.pkl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

